service:
 name: rushup

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-aws-documentation
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: eu-west-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 12 # optional, in seconds, default is 6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:261650959426:table/user_token"
    - Effect: Allow
      Action:
        - sns:SetEndpointAttributes
        - sns:GetEndpointAttributes
        - sns:CreatePlatformEndpoint
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:publish
      Resource: "arn:aws:sns:eu-west-1:261650959426:app/GCM/rush_up"
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: "*"
custom:
  defaultStage: dev
  profiles:
    dev: zeroandonedev
    prod: zeroandonedev
  documentation:
    models:
      -
        name: TokenRequest
        description: "Token Request that hold current user phone number and token provided by FCM/APN"
        contentType: "application/json"
        schema: ${file(models/tokenRequest.json)}
      -
        name: PushRequest
        description: "Push Request that hold both recipient phone number and Message to be sent"
        contentType: "application/json"
        schema: ${file(models/pushRequest.json)}
      -
        name: ContactSyncRequest
        description: "Contact Request that hold all Contacts Id and Phone to be checked against database and return Rushie Contacts"
        contentType: "application/json"
        schema: ${file(models/contactSyncRequest.json)}
      -
        name: ContactSyncResponse
        description: "Contact Response that hold all Rushie Contacts"
        contentType: "application/json"
        schema: ${file(models/contactSyncResponse.json)}
functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  publishMessage:
    handler: push.publish_message
    documentation:
      summary: "Send push notification to another Rushie User"
      description: "Push Notification to be sent to another User using Phone Number ane Message"
      requestBody:
        description: "Push Notification using PushRequest"
      requestModels:
        "application/json": PushRequest
    events:
      - http:
          path: publish
          method: post
          authorizer: aws_iam
  saveToken:
    handler: push.save_token
    documentation:
      summary: "Manage Endpoint platform"
      description: "Creates or update endpoint platform"
      requestBody:
        description: "Token Request that hold endpoint token"
      requestModels:
        "application/json": TokenRequest
    events:
      - http:
          path: token
          method: post
          authorizer: aws_iam
  contactSync:
    handler: contacts.sync
    documentation:
      summary: "Accept Map of Contacts Ids with phone Number and return a list of Rushie Contacts"
      description: "Compare Contacts against Rushie DB"
      requestBody:
        description: "Contact Sync Request that hold a map of Ids and Phone numbers"
      requestModels:
        "application/json": ContactSyncRequest
      methodResponses:
        -
          statusCode: '200'
          responseModels:
            "application/json": ContactSyncResponse
    events:
      - http:
          path: contact
          method: post
          authorizer: aws_iam
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}