service:
 name: rushup

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-aws-documentation
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: eu-west-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 12 # optional, in seconds, default is 6
  environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:eu-west-1:261650959426:table/user_token"
        - "arn:aws:dynamodb:eu-west-1:261650959426:table/delivery"
    - Effect: Allow
      Action:
        - sns:SetEndpointAttributes
        - sns:GetEndpointAttributes
        - sns:CreatePlatformEndpoint
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:publish
      Resource: "arn:aws:sns:eu-west-1:261650959426:app/GCM/rush_up"
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: "*"
    - Effect: Allow
      Action:
        - cognito-sync:ListRecords
      Resource: "arn:aws:cognito-sync:*:*:identitypool/*/identity/*/dataset/*"
custom:
  defaultStage: prod
  profiles:
    dev: zeroandonedev
    prod: zeroandonedev
  documentation:
    models:
      -
        name: TokenRequest
        contentType: "application/json"
        schema: ${file(models/tokenRequest.json)}
      -
        name: PushRequest
        contentType: "application/json"
        schema: ${file(models/pushRequest.json)}
      -
        name: ContactSyncRequest
        contentType: "application/json"
        schema: ${file(models/contactSyncRequest.json)}
      -
        name: ContactSyncResponse
        contentType: "application/json"
        schema: ${file(models/contactSyncResponse.json)}
      -
        name: DeliveryRequest
        contentType: "application/json"
        schema: ${file(models/deliveryRequest.json)}
      -
        name: DeliveryStatusRequest
        contentType: "application/json"
        schema: ${file(models/deliveryStatusRequest.json)}
functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  saveDelivery:
    handler: delivery.save_delivery
    events:
      - http:
          path: delivery
          method: post
          authorizer: aws_iam
          documentation:
            summary: "Save an approved delivery"
            requestModels:
              "application/json": DeliveryRequest
            methodResponses:
              - statusCode: '201'
                responseModels:
                  "application/json": DeliveryRequest
  updateDeliveryStatus:
    handler: delivery.update_delivery_status
    events:
      - http:
          path: delivery/{delivery_id}
          method: put
          request:
            parameters:
               paths:
                 delivery_id: true
          authorizer: aws_iam
          documentation:
            summary: "Update delivery report status"
            requestModels:
              "application/json": DeliveryStatusRequest
  publishMessage:
    handler: push.publish_message
    events:
      - http:
          path: publish
          method: post
          authorizer: aws_iam
          documentation:
            summary: "Send push notification to another Rushie User"
            requestModels:
              "application/json": PushRequest
  saveToken:
    handler: push.save_token
    events:
      - http:
          path: token
          method: post
          authorizer: aws_iam
          documentation:
            summary: "Manage Endpoint platform"
            requestModels:
              "application/json": TokenRequest
  contactSync:
    handler: contacts.sync
    events:
      - http:
          path: contact
          method: post
          authorizer: aws_iam
          documentation:
            summary: "Accept Map of Contacts Ids with phone Number and return a list of Rushie Contacts"
            requestBody:
              description: "Contact Sync Request that hold a map of Ids and Phone numbers"
            requestModels:
              "application/json": ContactSyncRequest
            methodResponses:
              - statusCode: '200'
                responseModels:
                  "application/json": ContactSyncResponse
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}