service: rushup

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: eu-west-2
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 12 # optional, in seconds, default is 6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:261650959426:table/rushup-mobilehub-1263655713-user-push"

custom:
  defaultStage: dev
  profiles:
    dev: zeroandonedev
    prod: technologyprod
functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  savePushData:
    handler: push.save_data
    events:
      - http:
          path: push/{phoneNumber}
          method: post
          request:
            parameters:
              paths:
                phoneNumber: true